#!/usr/bin/env bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit 1
fi

src=$(pwd)/$1

exists=$(find $src 2> /dev/null | wc -l)

tsr_tmp="/tmp/tsr_tmp/"

timestamp=$(date +%s)

uuid=$(cat /etc/timeshift/timeshift.json | jq '.backup_device_uuid')
dev=$(blkid | grep $uuid | awk '{print $1}' | sed 's/.$//')

mkdir -p "/run/timeshift/$timestamp/backup"
mount $dev "/run/timeshift/$timestamp/backup"

file=$(find /run/timeshift/*/backup/timeshift/snapshots/*/*$src -maxdepth 0 | sort -b | fzf)

if [ -z "$file" ] 
  then exit 1
fi

mkdir -p $tsr_tmp/$timestamp

if [ "$exists" = 1 ] 
   then cp -R -a -p -u $src $tsr_tmp/$timestamp/ && cp -R -u -p $file $src && stat $src
fi

if [ "$exists" = 0 ] 
   then cp -R -u -p $file $src
fi

umount $dev